## Feature Engineering on Daily Features of Folad Stock

In [1]:
import pandas as pd
import numpy as np

import datetime as datetime
import jdatetime as jdatetime

import pytse_client as tse

# To efficiently apply any function to a Pandas DataFrame or Series object in the quickest available method
import swifter as swifter

In [2]:
url = 'https://raw.githubusercontent.com/Hamtech-ai/iran-stock-market/Alireza_feature_extraction/dataset.csv'
foladData = pd.read_csv(url)
foladData.drop(foladData.index[:380], inplace=True)
foladData.head()

,Unnamed: 0,date,jdate,step,TEDPIX,open,close,high,low,adjClose,value,volume,count,yesterday,Enter_individual_money,Individual_buy_per_capita,Individual_sell_per_capita,Individual_buy_power_to_Individual_sell,label
380,380,2009-01-17,1387-10-28,381,8458.1,16.0,16.0,16.0,16.0,16.0,3868350987,1947009,100,16.0,-1.535234e+09,5.134134e+07,7.303626e+07,0.702957,0
381,381,2009-01-18,1387-10-29,382,8459.9,16.0,16.0,16.0,16.0,16.0,1610759752,810076,82,16.0,-3.089881e+08,8.015144e+07,2.851433e+07,2.810918,0
382,382,2009-01-19,1387-10-30,383,8467.4,16.0,17.0,17.0,16.0,16.0,1541413641,763741,64,16.0,-4.986258e+08,5.197989e+07,4.218423e+07,1.232211,0
383,383,2009-01-20,1387-11-01,384,8496.9,17.0,17.0,17.0,17.0,16.0,749587650,369255,24,16.0,-4.954012e+07,5.465876e+07,4.585598e+07,1.191966,0
384,384,2009-01-21,1387-11-02,385,8514.3,17.0,17.0,17.0,17.0,16.0,520517122,256034,23,16.0,-3.252800e+08,3.253952e+07,3.061865e+07,1.062735,0

In [3]:
foladData.shape

(3026, 19)

In [4]:
url_client = 'https://raw.githubusercontent.com/Hamtech-ai/iran-stock-market/Alireza_feature_extraction/foladClient.csv'
foladClient = pd.read_csv(url_client)
foladClient = foladClient.iloc[::-1]
foladClient.head()

,Unnamed: 0,date,individual_buy_count,corporate_buy_count,individual_sell_count,corporate_sell_count,individual_buy_vol,corporate_buy_vol,individual_sell_vol,corporate_sell_vol,individual_buy_value,corporate_buy_value,individual_sell_value,corporate_sell_value,individual_buy_mean_price,individual_sell_mean_price,corporate_buy_mean_price,corporate_sell_mean_price,individual_ownership_change
3025,3025,20081126,14,2,4,1,106338,20010,126338,10,248937258,46844120,295757258,24120,2341.000000,2341.0,2341.035482,2412.000000,-20000.0
3024,3024,20081129,116,175,3,2,4718258,33691903,121402,38288759,14980229312,107713006031,284080680,122409154663,3174.949168,2340.0,3196.999767,3196.999795,4596856.0
3023,3023,20081130,10,2,1,1,87219,12791,100000,10,204005241,29918859,233900000,24100,2339.000000,2339.0,2339.055508,2410.000000,-12781.0
3022,3022,20081201,8,1,5,1,128666,10,128666,10,300821108,24090,300821108,24090,2338.000000,2338.0,2409.000000,2409.000000,0.0
3021,3021,20081202,7,1,1,0,18553,10000,28553,0,43358361,23370000,66728361,0,2337.000000,2337.0,2337.000000,NaN,-10000.0

In [5]:
foladClient.shape

(3026, 19)

In [6]:
new_data = pd.concat([foladData,foladClient],axis=1)
new_data.head()

,Unnamed: 0,date,jdate,step,TEDPIX,open,close,high,low,adjClose,...,corporate_sell_vol,individual_buy_value,corporate_buy_value,individual_sell_value,corporate_sell_value,individual_buy_mean_price,individual_sell_mean_price,corporate_buy_mean_price,corporate_sell_mean_price,individual_ownership_change
380,380.0,2009-01-17,1387-10-28,381.0,8458.1,16.0,16.0,16.0,16.0,16.0,...,15932570.0,9.925658e+11,7.515742e+11,1.528292e+12,2.158476e+11,13507.762262,13496.712431,13496.683227,13547.572272,-39753274.0
381,381.0,2009-01-18,1387-10-29,382.0,8459.9,16.0,16.0,16.0,16.0,16.0,...,65259706.0,1.848472e+12,1.144838e+12,2.115209e+12,8.781011e+11,13525.829845,13610.306374,13627.462592,13455.486909,-18749942.0
382,382.0,2009-01-19,1387-10-30,383.0,8467.4,16.0,17.0,17.0,16.0,16.0,...,10279155.0,1.249052e+12,9.932880e+11,2.098035e+12,1.443041e+11,14019.339804,14028.934162,14042.411452,14038.517239,-60455705.0
383,383.0,2009-01-20,1387-11-01,384.0,8496.9,17.0,17.0,17.0,17.0,16.0,...,11143709.0,1.440149e+12,7.611477e+11,2.042807e+12,1.584892e+11,14253.380426,14257.376039,14257.616597,14222.300569,-42241630.0
384,384.0,2009-01-21,1387-11-02,385.0,8514.3,17.0,17.0,17.0,17.0,16.0,...,7539868.0,1.210179e+12,5.816010e+11,1.684139e+12,1.076405e+11,14322.734449,14332.968313,14343.734803,14276.184492,-33007520.0

In [7]:
def main_feature(new_data):
    print('main features')
    features = pd.DataFrame([])
    feature_info = dict()
    
    features = new_data[['date', 'open', 'close', 'high', 'low', 'adjClose',
                          'value', 'volume', 'count', 'individual_buy_count', 'individual_sell_count', 'individual_buy_vol',
                          'individual_sell_vol', 'individual_buy_value', 'individual_sell_value',
                          'yesterday', 'Individual_buy_per_capita', 'Individual_sell_per_capita']]
    feature_info = { \
                       'date':{'description':'date'}, \
                       'open':{'description':'open'}, \
                       'close':{'description':'close'}, \
                       'high':{'description':'high'}, \
                       'low':{'description':'low'}, \
                       'adjClose':{'description':'adjClose'}, \
                       'value':{'description':'value'}, \
                       'volume':{'description':'volume'}, \
                       'count':{'description':'count'}, \
                       'individual_buy_count':{'description':'individual_buy_count'}, \
                       'individual_sell_count':{'description':'individual_sell_count'}, \
                       'individual_buy_vol':{'description':'individual_buy_vol'}, \
                       'individual_sell_vol':{'description':'individual_sell_vol'}, \
                       'individual_buy_value':{'description':'individual_buy_value'}, \
                       'individual_sell_value':{'description':'individual_sell_value'}, \
                       'yesterday':{'description':'yesterday'}, \
                       'Individual_buy_per_capita':{'description':'Individual_buy_per_capita'}, \
                       'Individual_sell_per_capita':{'description':'Individual_sell_per_capita'}, \
                      }
        
    return features, feature_info

In [8]:
main_feature(new_data)

main features

(           date        date  open  close  high   low  adjClose         value  \
 380  2009-01-17  20201227.0  16.0   16.0  16.0  16.0      16.0  3.868351e+09
 381  2009-01-18  20201226.0  16.0   16.0  16.0  16.0      16.0  1.610760e+09
 382  2009-01-19  20201223.0  16.0   17.0  17.0  16.0      16.0  1.541414e+09
 383  2009-01-20  20201222.0  17.0   17.0  17.0  17.0      16.0  7.495876e+08
 384  2009-01-21  20201221.0  17.0   17.0  17.0  17.0      16.0  5.205171e+08
 ..          ...         ...   ...    ...   ...   ...       ...           ...
 4           NaN  20220903.0   NaN    NaN   NaN   NaN       NaN           NaN
 3           NaN  20220904.0   NaN    NaN   NaN   NaN       NaN           NaN
 2           NaN  20220905.0   NaN    NaN   NaN   NaN       NaN           NaN
 1           NaN  20220906.0   NaN    NaN   NaN   NaN       NaN           NaN
 0           NaN  20220907.0   NaN    NaN   NaN   NaN       NaN           NaN

         volume  count  individual_buy_count  individual_sell_count  \
 380  1947009.0  100.0                8499.0                12046.0
 381   810076.0   82.0                9896.0                15128.0
 382   763741.0   64.0                9656.0                13552.0
 383   369255.0   24.0                8166.0                12395.0
 384   256034.0   23.0                7481.0                10484.0
 ..         ...    ...                   ...                    ...
 4          NaN    NaN                2307.0                 1214.0
 3          NaN    NaN                2183.0                  775.0
 2          NaN    NaN                2007.0                  820.0
 1          NaN    NaN                1433.0                  925.0
 0          NaN    NaN                1449.0                  857.0

      individual_buy_vol  individual_sell_vol  individual_buy_value  \
 380          73481142.0          113234416.0          9.925658e+11
 381         136662346.0          155412288.0          1.848472e+12
 382          89094890.0          149550595.0          1.249052e+12
 383         101039103.0          143280733.0          1.440149e+12
 384          84493558.0          117501078.0          1.210179e+12
 ..                  ...                  ...                   ...
 4            42821782.0           56716425.0          2.175493e+11
 3            30862710.0           30396444.0          1.572501e+11
 2            34964184.0           34007836.0          1.777995e+11
 1            20280964.0           23545245.0          1.026170e+11
 0            32216792.0           18179929.0          1.629032e+11

      individual_sell_value  yesterday  Individual_buy_per_capita  \
 380           1.528292e+12       16.0               5.134134e+07
 381           2.115209e+12       16.0               8.015144e+07
 382           2.098035e+12       16.0               5.197989e+07
 383           2.042807e+12       16.0               5.465876e+07
 384           1.684139e+12       16.0               3.253952e+07
 ..                     ...        ...                        ...
 4             2.885442e+11        NaN                        NaN
 3             1.548327e+11        NaN                        NaN
 2             1.728321e+11        NaN                        NaN
 1             1.191153e+11        NaN                        NaN
 0             9.186660e+10        NaN                        NaN

      Individual_sell_per_capita
 380                7.303626e+07
 381                2.851433e+07
 382                4.218423e+07
 383                4.585598e+07
 384                3.061865e+07
 ..                          ...
 4                           NaN
 3                           NaN
 2                           NaN
 1                           NaN
 0                           NaN

 [3406 rows x 19 columns],
 {'date': {'description': 'date'},
  'open': {'description': 'open'},
  'close': {'description': 'close'},
  'high': {'description': 'high'},
  'low': {'description': 'low'},
  'adjClose': {'description': 'adjClose'},
  'value': {'description': 'value'},
  'volume': {'description': 'volume'},
  'count': {'description': 'count'},
  'individual_buy_count': {'description': 'individual_buy_count'},
  'individual_sell_count': {'description': 'individual_sell_count'},
  'individual_buy_vol': {'description': 'individual_buy_vol'},
  'individual_sell_vol': {'description': 'individual_sell_vol'},
  'individual_buy_value': {'description': 'individual_buy_value'},
  'individual_sell_value': {'description': 'individual_sell_value'},
  'yesterday': {'description': 'yesterday'},
  'Individual_buy_per_capita': {'description': 'Individual_buy_per_capita'},
  'Individual_sell_per_capita': {'description': 'Individual_sell_per_capita'}})

In [9]:
# Log is for better mapping to target prediction

def price_based_feature(new_data):
    print('price based features')
    features = pd.DataFrame([])
    feature_info = dict()
    
    def ret_based_func(new_data):
        df = new_data
        return_df = pd.DataFrame({\
                                  'ret1d_log':(np.log(df.adjClose) - np.log(df.yesterday)), \
                                  'ret3d_log':(np.log(df.adjClose) - np.log(df.yesterday)).rolling(3).sum(), \
                                  'ret7d_log':(np.log(df.adjClose) - np.log(df.yesterday)).rolling(7).sum(), \
                                  'ret14d_log':(np.log(df.adjClose) - np.log(df.yesterday)).rolling(14).sum(), \
                                  'ret30d_log':(np.log(df.adjClose) - np.log(df.yesterday)).rolling(30).sum(), \
                                  'ret60d_log':(np.log(df.adjClose) - np.log(df.yesterday)).rolling(60).sum(), \
                                  'ret90d_log':(np.log(df.adjClose) - np.log(df.yesterday)).rolling(90).sum(), \
                                  'ret120d_log':(np.log(df.adjClose) - np.log(df.yesterday)).rolling(120).sum(), \
                                  'ret300d_log':(np.log(df.adjClose) - np.log(df.yesterday)).rolling(300).sum(), \
                                  'lastclose_log':(np.log(df['adjClose']) - np.log(df['close'])), \
                                  'buy_queue_locked' : np.logical_and(np.isclose(df['high'], df['low']), df['high'] > df['yesterday']), \
                                  'sell_queue_locked' : np.logical_and(np.isclose(df['high'], df['low']), df['low'] < df['yesterday']), \
                                  })
        return return_df
    
    feature_info = {\
            'ret1d_log':{'description':'return per day with respect to 1 day before.'}, \
            'ret3d_log':{'description':'return per day with respect to 3 day before.'}, \
            'ret7d_log':{'description':'return per day with respect to 7 day before.'}, \
            'ret14d_log':{'description':'return per day with respect to 14 day before.'}, \
            'ret30d_log':{'description':'return per day with respect to 30 days before.'}, \
            'ret60d_log':{'description':'return per day with respect to 60 days before.'}, \
            'ret90d_log':{'description':'return per day with respect to 90 days before.'}, \
            'ret120d_log':{'description':'return per day with respect to 120 days before.'}, \
            'ret300d_log':{'description':'return per day with respect to 300 days before.'}, \
            'lastclose_log':{'description':'last-to-close ratio log.'}, \
            'buy_queue_locked':{'description':'indicates whether the trades are in buying queue.'}, \
            'sell_queue_locked':{'description':'indicates whether the trades are in selling queue.'}, \
            }
    price_features = ret_based_func(new_data)
    return price_features , feature_info

In [10]:
price_based_feature(new_data)

price based features

(     ret1d_log  ret3d_log  ret7d_log  ret14d_log  ret30d_log  ret60d_log  \
 380        0.0        NaN        NaN         NaN         NaN         NaN
 381        0.0        NaN        NaN         NaN         NaN         NaN
 382        0.0        0.0        NaN         NaN         NaN         NaN
 383        0.0        0.0        NaN         NaN         NaN         NaN
 384        0.0        0.0        NaN         NaN         NaN         NaN
 ..         ...        ...        ...         ...         ...         ...
 4          NaN        NaN        NaN         NaN         NaN         NaN
 3          NaN        NaN        NaN         NaN         NaN         NaN
 2          NaN        NaN        NaN         NaN         NaN         NaN
 1          NaN        NaN        NaN         NaN         NaN         NaN
 0          NaN        NaN        NaN         NaN         NaN         NaN

      ret90d_log  ret120d_log  ret300d_log  lastclose_log  buy_queue_locked  \
 380         NaN          NaN          NaN       0.000000             False
 381         NaN          NaN          NaN       0.000000             False
 382         NaN          NaN          NaN      -0.060625             False
 383         NaN          NaN          NaN      -0.060625              True
 384         NaN          NaN          NaN      -0.060625              True
 ..          ...          ...          ...            ...               ...
 4           NaN          NaN          NaN            NaN             False
 3           NaN          NaN          NaN            NaN             False
 2           NaN          NaN          NaN            NaN             False
 1           NaN          NaN          NaN            NaN             False
 0           NaN          NaN          NaN            NaN             False

      sell_queue_locked
 380              False
 381              False
 382              False
 383              False
 384              False
 ..                 ...
 4                False
 3                False
 2                False
 1                False
 0                False

 [3406 rows x 12 columns],
 {'ret1d_log': {'description': 'return per day with respect to 1 day before.'},
  'ret3d_log': {'description': 'return per day with respect to 3 day before.'},
  'ret7d_log': {'description': 'return per day with respect to 7 day before.'},
  'ret14d_log': {'description': 'return per day with respect to 14 day before.'},
  'ret30d_log': {'description': 'return per day with respect to 30 days before.'},
  'ret60d_log': {'description': 'return per day with respect to 60 days before.'},
  'ret90d_log': {'description': 'return per day with respect to 90 days before.'},
  'ret120d_log': {'description': 'return per day with respect to 120 days before.'},
  'ret300d_log': {'description': 'return per day with respect to 300 days before.'},
  'lastclose_log': {'description': 'last-to-close ratio log.'},
  'buy_queue_locked': {'description': 'indicates whether the trades are in buying queue.'},
  'sell_queue_locked': {'description': 'indicates whether the trades are in selling queue.'}})

In [11]:
def proportion_based_feature(foladData):
    print('proportion based features')
    features = pd.DataFrame([])
    feature_info = dict()

    def prp_based_func(foladData):
        df = foladData
        df.index = [pd.Timestamp(item) for item in df['date']]
        return_df = pd.DataFrame({\
            'prp_high30d':df['adjClose']/df['high'].rolling('30d').max(), \
            'prp_high60d':df['adjClose']/df['high'].rolling('60d').max(), \
            'prp_high90d':df['adjClose']/df['high'].rolling('90d').max(), \
            'prp_high120d':df['adjClose']/df['high'].rolling('120d').max(), \
            'prp_high300d':df['adjClose']/df['high'].rolling('300d').max(), \
            'prp_low30d':df['adjClose']/df['low'].rolling('30d').min(), \
            'prp_low60d':df['adjClose']/df['low'].rolling('60d').min(), \
            'prp_low90d':df['adjClose']/df['low'].rolling('90d').min(), \
            'prp_low120d':df['adjClose']/df['low'].rolling('120d').min(), \
            'prp_low300d':df['adjClose']/df['low'].rolling('300d').min(), \
            'prp_value3d30d':df['value'].rolling('3d').mean()/df['value'].rolling('30d').mean(), \
            'prp_value5d60d':df['value'].rolling('5d').mean()/df['value'].rolling('60d').mean(), \
            'prp_value15d120d':df['value'].rolling('15d').mean()/df['value'].rolling('120d').mean(), \
            'prp_value30d200d':df['value'].rolling('30d').mean()/df['value'].rolling('200d').mean(), \
            })
        return return_df
    
    feature_ifo = {\
            'prp_high30d':{'description':'ratio of close_price to maximum of high prices in 30-day period.'}, \
            'prp_high60d':{'description':'ratio of close_price to maximum of high prices in 60-day period.'}, \
            'prp_high90d':{'description':'ratio of close_price to maximum of high prices in 90-day period.'}, \
            'prp_high120d':{'description':'ratio of close_price to maximum of high prices in 120-day period.'}, \
            'prp_high300d':{'description':'ratio of close_price to maximum of high prices in 300-day period.'}, \
            'prp_low30d':{'description':'ratio of close_price to minimum of low prices in 30-day period.'}, \
            'prp_low60d':{'description':'ratio of close_price to minimum of low prices in 60-day period.'}, \
            'prp_low90d':{'description':'ratio of close_price to minimum of low prices in 90-day period.'}, \
            'prp_low120d':{'description':'ratio of close_price to minimum of low prices in 120-day period.'}, \
            'prp_low300d':{'description':'ratio of close_price to minimum of low prices in 300-day period.'}, \
            'prp_value3d30d':{'description':'ratio of 3-day average value to 30-day average value'}, \
            'prp_value5d60d':{'description':'ratio of 5-day average value to 60-day average value'}, \
            'prp_value15d120d':{'description':'ratio of 15-day average value to 120-day average value'}, \
            'prp_value30d200d':{'description':'ratio of 30-day average value to 200-day average value'}, \
            }
    prop_features = prp_based_func(foladData)
    return prop_features, feature_info

In [12]:
proportion_based_feature(foladData)

proportion based features

(            prp_high30d  prp_high60d  prp_high90d  prp_high120d  prp_high300d  \
 2009-01-17     1.000000     1.000000     1.000000      1.000000      1.000000
 2009-01-18     1.000000     1.000000     1.000000      1.000000      1.000000
 2009-01-19     0.941176     0.941176     0.941176      0.941176      0.941176
 2009-01-20     0.941176     0.941176     0.941176      0.941176      0.941176
 2009-01-21     0.941176     0.941176     0.941176      0.941176      0.941176
 ...                 ...          ...          ...           ...           ...
 2022-08-24     0.911111     0.911111     0.911111      0.881429      0.881429
 2022-08-27     0.911111     0.911111     0.911111      0.881429      0.881429
 2022-08-28     0.900855     0.900855     0.900855      0.871507      0.871507
 2022-08-29     0.894017     0.894017     0.894017      0.864892      0.864892
 2022-08-30     0.883761     0.883761     0.883761      0.854969      0.854969

             prp_low30d  prp_low60d  prp_low90d  prp_low120d  prp_low300d  \
 2009-01-17    1.000000    1.000000    1.000000     1.000000     1.000000
 2009-01-18    1.000000    1.000000    1.000000     1.000000     1.000000
 2009-01-19    1.000000    1.000000    1.000000     1.000000     1.000000
 2009-01-20    1.000000    1.000000    1.000000     1.000000     1.000000
 2009-01-21    1.000000    1.000000    1.000000     1.000000     1.000000
 ...                ...         ...         ...          ...          ...
 2022-08-24    1.071788    1.082014    1.082014     1.082014     1.248536
 2022-08-27    1.062812    1.082014    1.082014     1.082014     1.248536
 2022-08-28    1.050847    1.069834    1.069834     1.069834     1.234481
 2022-08-29    1.042871    1.061713    1.061713     1.061713     1.225111
 2022-08-30    1.007797    1.049533    1.049533     1.049533     1.211056

             prp_value3d30d  prp_value5d60d  prp_value15d120d  prp_value30d200d
 2009-01-17        1.000000        1.000000          1.000000          1.000000
 2009-01-18        1.000000        1.000000          1.000000          1.000000
 2009-01-19        1.000000        1.000000          1.000000          1.000000
 2009-01-20        0.669533        1.000000          1.000000          1.000000
 2009-01-21        0.565200        1.000000          1.000000          1.000000
 ...                    ...             ...               ...               ...
 2022-08-24        0.781243        0.692817          0.628917          0.728975
 2022-08-27        0.498958        0.560978          0.599818          0.743351
 2022-08-28        0.503258        0.525413          0.519337          0.720339
 2022-08-29        0.517469        0.472937          0.509968          0.699082
 2022-08-30        0.602697        0.467527          0.491901          0.572881

 [3026 rows x 14 columns],
 {})